power = read.table("household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?", stringsAsFactors = FALSE)
power$DateTime = strptime(paste(power[,1], power[,2]), "%e/%m/%Y %H:%M:%S")
power$Date = as.Date(strptime(power$Date, "%e/%m/%Y"))
sub = subset(power, Date >= "2007-02-01" & Date <= "2007-02-02")
png(filename = "plot3.png")
plot(sub$DateTime,sub$Sub_metering_1, xlab = "", ylab = "Energy sub metering", type = "n")
lines(sub$DateTime,sub$Sub_metering_1)
lines(sub$DateTime,sub$Sub_metering_2, col = "red")
lines(sub$DateTime,sub$Sub_metering_3, col = "blue")
legend("topright", col = c("black","blue", "red"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"),lty = c(1,1,1))
dev.off()
