power = read.table("household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?", stringsAsFactors = FALSE)
power$DateTime = strptime(paste(power[,1], power[,2]), "%e/%m/%Y %H:%M:%S")
power$Date = as.Date(strptime(power$Date, "%e/%m/%Y"))
sub = subset(power, Date >= "2007-02-01" & Date <= "2007-02-02")
png(filename = "plot4.png")
par(mfrow = c(2,2))
plot(sub$DateTime,sub$Global_active_power, xlab = "", ylab = "Global Active Power (kilowatts)", type = "n")
lines(sub$DateTime,sub$Global_active_power)
plot(sub$DateTime, sub$Voltage, xlab = "datetime", ylab = "Voltage", type = "n")
lines(sub$DateTime, sub$Voltage)
plot(sub$DateTime,sub$Sub_metering_1, xlab = "", ylab = "Energy sub metering", type = "n")
lines(sub$DateTime,sub$Sub_metering_1)
lines(sub$DateTime,sub$Sub_metering_2, col = "red")
lines(sub$DateTime,sub$Sub_metering_3, col = "blue")
legend("topright", col = c("black","blue", "red"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"),lty = c(1,1,1), bty ="n",cex = 0.4)
plot(sub$DateTime,sub$Global_reactive_power, xlab = "datetime", ylab = "Global Reactive Power", type = "n")
lines(sub$DateTime, sub$Global_reactive_power)
dev.off()